package com.bawei.zhangyiman20200106.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.zhangyiman20200106.model.dao.OneDao;
import com.bawei.zhangyiman20200106.model.dao.TwoDao;

import com.bawei.zhangyiman20200106.database.OneDaoDao;
import com.bawei.zhangyiman20200106.database.TwoDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig oneDaoDaoConfig;
    private final DaoConfig twoDaoDaoConfig;

    private final OneDaoDao oneDaoDao;
    private final TwoDaoDao twoDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        oneDaoDaoConfig = daoConfigMap.get(OneDaoDao.class).clone();
        oneDaoDaoConfig.initIdentityScope(type);

        twoDaoDaoConfig = daoConfigMap.get(TwoDaoDao.class).clone();
        twoDaoDaoConfig.initIdentityScope(type);

        oneDaoDao = new OneDaoDao(oneDaoDaoConfig, this);
        twoDaoDao = new TwoDaoDao(twoDaoDaoConfig, this);

        registerDao(OneDao.class, oneDaoDao);
        registerDao(TwoDao.class, twoDaoDao);
    }
    
    public void clear() {
        oneDaoDaoConfig.clearIdentityScope();
        twoDaoDaoConfig.clearIdentityScope();
    }

    public OneDaoDao getOneDaoDao() {
        return oneDaoDao;
    }

    public TwoDaoDao getTwoDaoDao() {
        return twoDaoDao;
    }

}
